changes

diff --git a/bin/update_postgres_schema_from_dev b/bin/update_postgres_schema_from_dev
--- a/bin/update_postgres_schema_from_dev
+++ b/bin/update_postgres_schema_from_dev
@@ -1,21 +1,40 @@
-#!/usr/bin/env bash
+#!/usr/bin/env zsh
 set -eu
 
+zparseopts -D -E -F d:=DB_NAME -help=HELP
+[[ -n $HELP ]] && cat <<EOF && exit 0 || true
+Usage: update_postgres_schema_from_dev [-d<dbname>] [--help]
+
+    -d <dbname>
+        Name of the database to export to, default postgres
+    --help
+        Print this message
+EOF
+
+[[ -n $DB_NAME ]] && DB_NAME=${DB_NAME[2]}
+[[ -z $DB_NAME ]] && DB_NAME="postgres"
+
+source "$(dirname -- "$0")/helpers.zsh"
+
 POSTGRES_APP_BIN="/Applications/Postgres.app/Contents/Versions/latest/bin/pg_dump"
-DB_NAME="quorum_$(whoami)"
-
-export PGPASSWORD="$(grep 'DEV_DB_PASSWORD \=' quorum/settings/base_settings.py | sed 's/^.* "//' | sed 's/".*$//')"
 [[ -d "$POSTGRES_APP_BIN" ]] && PATH="$PATH:$POSTGRES_APP_BIN"
+which pg_dump >/dev/null || die "Unable to find pg_dump on your path"
 
-SCHEMA_FILE="$(mktemp)"
-
+SCHEMA_FILE="$HOME/dev/schema.sql"
 echo "Schema file will be output to $SCHEMA_FILE"
+
 echo "Step 1: Dump database to the schema file"
+export PGPASSWORD="$(get_dev_db_password)"
 pg_dump -s -h 127.0.0.1 -U quorum_user -d quorum_db -f "$SCHEMA_FILE" -p 5433 -v
+PGPASSWORD=
+
 echo "Step 2: Drop exisitng database $DB_NAME if exists"
-dropdb $DB_NAME || echo "dropdb command failed, ignoring (DB probably already existed)"
+dropdb $DB_NAME || echo "dropdb command failed, ignoring (DB probably didn't exist)"
+
 echo "Step 3: Create database $DB_NAME"
 createdb $DB_NAME
+
 echo "Step 4: Load schema"
 psql  -f "$SCHEMA_FILE"
+
 echo "Done."
